name: Build Run Sheets
on:
  push:
    branches: ["main"]
    paths:
      - 'content/**'
      - 'cmd/render-slides/**'
      - 'cmd/run_sheets/**'
      - 'scripts/generate_run_sheets.sh'
      - 'scripts/generate_run_sheets_html.sh'
      - 'scripts/generate_website_index.sh'
      - 'scripts/deploy_website.sh'
      - 'scripts/install_chrome.sh'
      - '.github/workflows/run_sheets.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm ffmpeg jq fonts-dejavu-core poppler-utils rsync
          sudo npm install -g @marp-team/marp-cli
          ./scripts/install_chrome.sh
          go mod download
      - name: Verify fonts
        run: |
          ls -l /usr/share/fonts/truetype/dejavu/DejaVuSans*.ttf
          fc-list | grep -i dejavu | head
      - name: Build
        run: |
          go vet ./...
          go build ./cmd/render-slides
          go build ./cmd/run_sheets
      - name: Generate run sheets
        run: |
          ./scripts/generate_run_sheets.sh
      - name: Convert run sheets to HTML
        run: |
          ./scripts/generate_run_sheets_html.sh
      - name: Update website index
        run: |
          ./scripts/generate_website_index.sh
      - name: Prepare SSH key
        env:
          DEPLOYMENT_SSH_KEY: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        run: |
          echo "$DEPLOYMENT_SSH_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          echo "DEPLOYMENT_SSH_KEY=/tmp/deploy_key" >> $GITHUB_ENV
      - name: Deploy website
        run: |
          ./scripts/deploy_website.sh
          rm -f /tmp/deploy_key
      - uses: actions/upload-artifact@v4
        with:
          name: run-sheets
          path: run-sheets/*.pdf
